package com.elasticSearch.crud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "student")
public class Student {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String sid;
	@DynamoDBAttribute
	private String sname;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private String mobile;
	public String getSid() {
		return sid;
	}
	public void setSid(String sid) {
		this.sid = sid;
	}
	public String getSname() {
		return sname;
	}
	public void setSname(String sname) {
		this.sname = sname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public Student(String sid, String sname, String email, String mobile) {
		super();
		this.sid = sid;
		this.sname = sname;
		this.email = email;
		this.mobile = mobile;
	}
	public Student() {
		super();
	}
	
	
	

}
